# Welcome to Serverless!
# This file is the main config file for your service.

service: serverless-reminders

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:*"
      Resource:
        - "*"
functions:
  dailyReminder:
    handler: handler.sendReminderDaily
    event:
      # Invoke the Lambda function everyday
      - scheduled: rate(1 day)
  weekendReminder:
    handler: handler.sendReminderWeekend
    event:
      # Invoke the Lambda function every weekend at 1pm US/Eastern Time
      - scheduled: cron(30 22 ? * SUN, SAT *)